language: ruby
rvm:
  - 2.2.2

cache:
  bundler: true
  directories:
    - node_modules

install:
  - bundle install
  - npm install

script:
  - npm run dev
  - npm test
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "siteleaf" ]; then npm run prod; fi

env:
  global:
    - secure: IrOjVgWHGCwqzLjdaZYBIPR9d1AGuVFxP78LGDIDfxv/Yh1VM6C/JVBbo/jEmj7Fp0vCHOcTQX3zWGZ02T0O7+QAj79EMq3zo84uOy8v4vtPnsl8YOkzNzaD0HfNqxeJBZSwup/V+aTVFgvdSFXS6A1Nx209Pusi92GE4G8gngegmrorvcAK2v4QFa2NG5YsE+krL7m2j/gGNSidfzWvhNqKdTBhMgoNRs4y73RjS04RgEKaDBHhyEgZmrxktzd6P88GRnUhXL8EsO0NjNUm0AKg9Hqn3Sn+oeWCUug/D8lWKtr6yaDX6VooITzqUrzzu5i0bAzMug3Exvmpx7pXGKvvg8MFD+UlPKsOz+/4nMMaaldgHlkXqqTj1JegQ/s5JB6vkj0kuw2KuMrcTEmQlMRrdfONSQv0iZ34jBPIovJWc87Dhjc86A/EnGvgxsckA3fON4svWkcybGrCUG1OEg3LRr1rOrsvPXLu/ULN5MrFh7+pu2DDFN+PpA44zfDNuc5suWawsSyyKlwQaVOCCNk9rYH1ZMe/6GzfxpMDNW1mNxkcAKtNbTYOgAOpbR6iLHQa95wDOjCZjr+rnnuCR24l4gLyEiRe2l9QCfAFJA5mS5BzwU+zeRHuoGGs8zQh7XNK81EZc43S0JGU50v6dXZgTjcfzTSEdBbM3W10xiw=
    - secure: AA9fggxL/JGK9XBTPbrPuzVoTu+VIXK2pv5gHG8azDSUCOUGbyhJ0kfznWXC67ygBeWgOOjU8KBypRTK2ud+PuOaMVlUyDQUEvD8s5wsoKkDsBo/0OvFDbNe0fRDq9j9J5p1pEAOPWHrCActiS7+L34anfyO2mMDdsBr2BaQ35pjDrhKjZDEVRYKaxlYsucMkV7YvnxAwhYTxn0v73cVPzcq6PhVRl+wVAxwbdYrsSJtLG1ga7QswBwWseXyZYSxqAchBFTL9kOk6dOcNhiq5f6hiKcE4//c0dgWASgszdY9QI5/hmSMrQSUdzBDW1VT69wJDVCSTl7CBx/v5xFpWBBH42LAd/3d8CcR8qcSGwCiv+x6Qq7EYbvdi3C3ll/5atGtjp8kr2FR3PgBk+HNCb+EkbM5L0M3Sl7hz+WF6zul2MMPK15HWpxl8tihFjakzsYflIYL3Uwg67Vc65+f8whwWMVbF1G5Ak9EaqdYJfuss/NLejE7YIP0N0Aoyr/fl3VcABlLgioSHC15tJ4Dy9JiAuH6uYTq3QT7uKe6DpX360KIV8e9Ap8ZP/TFkcCz/7EBKBMsnhByAyXPOgM3jZRZPna57w/ZtMwxAvepwKgxuI2+mhG6+9y0AZr8D9Gnp+qWdxev8R4xcWxAFSzH2djpb7lr8BNnCSyk6aG8yYA=
