---
title: Anything For Now
url: http://anythingfornow.com
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: false
  objects:
    title: Objects
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    unique_id: ''
    author: ''
    image:
    - alt: ''
      asset: ''
- scope:
    path: ''
    type: objects
  values:
    image:
    - alt: ''
      asset: ''
license:
  short: CC BY-NC 4.0
  long: Creative Commons Attribution-NonCommercial 4.0 International
link:
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
  subscribe:
    full: "/full.xml"
gems:
- sass
- jekyll/imgix
- jekyll-archives
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/:year/:month/:title/"
sass:
  sass_dir: _source/scss
  style: compressed
include:
- _feeds
- _pages
exclude:
- Gemfile*
- node_modules
- package.json
domain: anythingfornow.com
patterns_url: "/patterns"
image_url: "/uploads"
icon_url: "/icons"
resources_url: "/resources"
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
