###### TODO add a site description
title: Anything For Now
timezone: America/New_York

license:
  short: 'CC BY-NC 4.0'
  long: 'Creative Commons Attribution-NonCommercial 4.0 International'

# Content

## Referenced URLs (internal and external links for inline use)
link:
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
  subscribe:
    full: /full.xml

# Site configuration

## Gems configuration
gems:
  - sass
  - jekyll/imgix

## Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

## Permalink configuration
permalink: /:year/:month/:title/

collections:
  authors:
    title: Authors
    output: false
  objects:
    title: Objects
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      unique_id: ''
      author: ''
      image:
        - alt: ''
          asset: ''
  -
    scope:
      path: ''
      type: 'objects'
    values:
      image:
        - alt: ''
          asset: ''

## Sass configuration
sass:
  sass_dir: _source/scss
  style: compressed

## Project configuration
include:
  - _feeds
  - _pages

exclude:
  - Gemfile*
  - node_modules
  - package.json

## Configuration URLs
domain: 'anythingfornow.com'
url: 'http://anythingfornow.com'
patterns_url: /patterns
image_url: /uploads
icon_url: /icons
resources_url: /resources

###### TODO https://www.google.com/webmasters/verification
## Google site verification
google_verification: ''
